# Указываем версию синтаксиса
version: '3.8'

# Описываем наши сервисы (в данном случае только один - база данных)
services:
  db:
    image: postgres:15      # Используем официальный образ PostgreSQL версии 15
    container_name: aifinder_db # Название нашего контейнера для удобства
    environment:              # Переменные окружения для настройки базы данных
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aifinder_db
    ports:
      - "5432:5432"           # Пробрасываем порт с контейнера на наш компьютер