version: "3.9"

services:
  pg:
    image: postgres:17
    container_name: aifinder_pg17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qweQWE123
      POSTGRES_DB: aifinder_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

    # Пробрасываем порт с контейнера на наш компьютер