"""Add short_description to ToolTranslation

Revision ID: 048cdc7f935c
Revises: 546d1686c8c3
Create Date: 2025-07-09 22:03:05.797109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '048cdc7f935c'
down_revision: Union[str, None] = '546d1686c8c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool_translations', sa.Column('short_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool_translations', 'short_description')
    # ### end Alembic commands ###
