"""Add reviews and rating fields

Revision ID: 8c658ab3a897
Revises: e90dd3623e10
Create Date: 2025-06-29 18:43:04.824782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c658ab3a897'
down_revision: Union[str, None] = 'e90dd3623e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('reviews',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('text', sa.String(), nullable=True),
    # sa.Column('rating', sa.Integer(), nullable=False),
    # sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    # sa.Column('tool_id', sa.Integer(), nullable=False),
    # sa.Column('author_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    # sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    # op.drop_index(op.f('ix_comments_id'), table_name='comments')
    # op.drop_table('comments')
    # op.add_column('tools', sa.Column('average_rating', sa.Float(), nullable=True))
    # op.drop_column('tools', 'rating')
    # op.drop_column('tools', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tools', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('tools', 'average_rating')
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('tool_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('comments_author_id_fkey')),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('comments_tool_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('comments_pkey'))
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
