"""Add indexes to tool_translations for name and description

Revision ID: b193fcc48bc3
Revises: 8c658ab3a897
Create Date: 2025-07-03 19:19:59.920946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b193fcc48bc3'
down_revision: Union[str, None] = '8c658ab3a897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # create index if not exists to avoid duplicate errors
    op.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_tool_translations_name ON tool_translations (name)"))
    op.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_tool_translations_description ON tool_translations (description)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tool_translations_name', table_name='tool_translations')
    op.drop_index('ix_tool_translations_description', table_name='tool_translations')
    # ### end Alembic commands ###
