"""Add pricing and platforms to Tool model

Revision ID: e90dd3623e10
Revises: 79d6de74cede
Create Date: 2025-06-29 15:31:35.651745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e90dd3623e10'
down_revision: Union[str, None] = '79d6de74cede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('pricing_model', sa.Enum('FREE', 'FREEMIUM', 'PAID', 'TRIAL', name='pricingmodel'),
                                     nullable=False, server_default='FREE'))
    op.add_column('tools', sa.Column('platforms', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'platforms')
    op.drop_column('tools', 'pricing_model')
    # ### end Alembic commands ###
